# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"param_locs": "00_core.ipynb",
         "docments": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://fastai.github.io/docments/"

git_url = "https://github.com/fastai/docments/tree/master/"

def custom_doc_links(name): return None
